name: React-Tetris Deploy Pipe
on:
  push:
    tags:
      - "latest"
      - "v*"

jobs: 
  Build-and-Push-React-tetris-to-docker-hub:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-tetris-docker
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name/app
          tags: |
            type=semver,pattern={{latest}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to Docker-hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v5
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-tetris-image:${{ steps.meta.outputs.tags }}
          
      